# Generated by Django 2.1.7 on 2019-04-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_remove_blog_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
